//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityEditorEx.src.editor.Templates {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    public partial class StateMachineState_cs : StateMachineState_csBase {
        
        
        private string _namespacenameField;

        public string namespacename {
            get {
                return this._namespacenameField;
            }
        }

        private string _statenameField;

        public string statename {
            get {
                return this._statenameField;
            }
        }

        private string _statemachinetypeField;

        public string statemachinetype {
            get {
                return this._statemachinetypeField;
            }
        }

        private string _controllertypeField;

        public string controllertype {
            get {
                return this._controllertypeField;
            }
        }

        private bool _partialField;

        public bool @partial {
            get {
                return this._partialField;
            }
        }

        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 12 ""
            this.Write("using System.Collections;\nusing System.Collections.Generic;\nusing UnityEngine;\nus" +
                    "ing UnityEngineEx;\n\n\n\nnamespace ");
            
            #line default
            #line hidden
            
            #line 19 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( this.namespacename ));
            
            #line default
            #line hidden
            
            #line 19 ""
            this.Write("\n{\n    public class ");
            
            #line default
            #line hidden
            
            #line 21 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( this.statename ));
            
            #line default
            #line hidden
            
            #line 21 ""
            this.Write(" : ");
            
            #line default
            #line hidden
            
            #line 21 ""
 if (this.partial) { 
            
            #line default
            #line hidden
            
            #line 22 ""
            this.Write("StateMachineBehaviour /* ");
            
            #line default
            #line hidden
            
            #line 22 ""
 } 
            
            #line default
            #line hidden
            
            #line 23 ""
            this.Write("BaseState<");
            
            #line default
            #line hidden
            
            #line 23 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( this.statemachinetype ));
            
            #line default
            #line hidden
            
            #line 23 ""
            this.Write(", ");
            
            #line default
            #line hidden
            
            #line 23 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( this.controllertype ));
            
            #line default
            #line hidden
            
            #line 23 ""
            this.Write(">");
            
            #line default
            #line hidden
            
            #line 23 ""
 if (this.partial) { 
            
            #line default
            #line hidden
            
            #line 24 ""
            this.Write(" */ ");
            
            #line default
            #line hidden
            
            #line 24 ""
 } 
            
            #line default
            #line hidden
            
            #line 25 ""
            this.Write("    {\n    }\n}\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
            if ((this.Errors.HasErrors == false)) {
                bool _namespacenameAcquired = false;
                if (((this.Session != null) 
                            && this.Session.ContainsKey("namespacename"))) {
                    object data = this.Session["namespacename"];
                    if (typeof(string).IsAssignableFrom(data.GetType())) {
                        this._namespacenameField = ((string)(data));
                        _namespacenameAcquired = true;
                    }
                    else {
                        this.Error("The type \'System.String\' of the parameter \'namespacename\' did not match the type " +
                                "passed to the template");
                    }
                }
                if ((_namespacenameAcquired == false)) {
                    object data = System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("namespacename");
                    if ((data != null)) {
                        if (typeof(string).IsAssignableFrom(data.GetType())) {
                            this._namespacenameField = ((string)(data));
                            _namespacenameAcquired = true;
                        }
                        else {
                            this.Error("The type \'System.String\' of the parameter \'namespacename\' did not match the type " +
                                    "passed to the template");
                        }
                    }
                }
                bool _statenameAcquired = false;
                if (((this.Session != null) 
                            && this.Session.ContainsKey("statename"))) {
                    object data = this.Session["statename"];
                    if (typeof(string).IsAssignableFrom(data.GetType())) {
                        this._statenameField = ((string)(data));
                        _statenameAcquired = true;
                    }
                    else {
                        this.Error("The type \'System.String\' of the parameter \'statename\' did not match the type pass" +
                                "ed to the template");
                    }
                }
                if ((_statenameAcquired == false)) {
                    object data = System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("statename");
                    if ((data != null)) {
                        if (typeof(string).IsAssignableFrom(data.GetType())) {
                            this._statenameField = ((string)(data));
                            _statenameAcquired = true;
                        }
                        else {
                            this.Error("The type \'System.String\' of the parameter \'statename\' did not match the type pass" +
                                    "ed to the template");
                        }
                    }
                }
                bool _statemachinetypeAcquired = false;
                if (((this.Session != null) 
                            && this.Session.ContainsKey("statemachinetype"))) {
                    object data = this.Session["statemachinetype"];
                    if (typeof(string).IsAssignableFrom(data.GetType())) {
                        this._statemachinetypeField = ((string)(data));
                        _statemachinetypeAcquired = true;
                    }
                    else {
                        this.Error("The type \'System.String\' of the parameter \'statemachinetype\' did not match the ty" +
                                "pe passed to the template");
                    }
                }
                if ((_statemachinetypeAcquired == false)) {
                    object data = System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("statemachinetype");
                    if ((data != null)) {
                        if (typeof(string).IsAssignableFrom(data.GetType())) {
                            this._statemachinetypeField = ((string)(data));
                            _statemachinetypeAcquired = true;
                        }
                        else {
                            this.Error("The type \'System.String\' of the parameter \'statemachinetype\' did not match the ty" +
                                    "pe passed to the template");
                        }
                    }
                }
                bool _controllertypeAcquired = false;
                if (((this.Session != null) 
                            && this.Session.ContainsKey("controllertype"))) {
                    object data = this.Session["controllertype"];
                    if (typeof(string).IsAssignableFrom(data.GetType())) {
                        this._controllertypeField = ((string)(data));
                        _controllertypeAcquired = true;
                    }
                    else {
                        this.Error("The type \'System.String\' of the parameter \'controllertype\' did not match the type" +
                                " passed to the template");
                    }
                }
                if ((_controllertypeAcquired == false)) {
                    object data = System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("controllertype");
                    if ((data != null)) {
                        if (typeof(string).IsAssignableFrom(data.GetType())) {
                            this._controllertypeField = ((string)(data));
                            _controllertypeAcquired = true;
                        }
                        else {
                            this.Error("The type \'System.String\' of the parameter \'controllertype\' did not match the type" +
                                    " passed to the template");
                        }
                    }
                }
                bool _partialAcquired = false;
                if (((this.Session != null) 
                            && this.Session.ContainsKey("partial"))) {
                    object data = this.Session["partial"];
                    if (typeof(bool).IsAssignableFrom(data.GetType())) {
                        this._partialField = ((bool)(data));
                        _partialAcquired = true;
                    }
                    else {
                        this.Error("The type \'System.Boolean\' of the parameter \'partial\' did not match the type passe" +
                                "d to the template");
                    }
                }
                if ((_partialAcquired == false)) {
                    object data = System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("partial");
                    if ((data != null)) {
                        if (typeof(bool).IsAssignableFrom(data.GetType())) {
                            this._partialField = ((bool)(data));
                            _partialAcquired = true;
                        }
                        else {
                            this.Error("The type \'System.Boolean\' of the parameter \'partial\' did not match the type passe" +
                                    "d to the template");
                        }
                    }
                }
            }

        }
    }
    
    public class StateMachineState_csBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
